corrected mysql driver
git-svn-id: svn+ssh://svn.code.sf.net/p/xsb/src/trunk@5851 756869e0-9e47-4bc5-b0a8-847305dc5e1c

diff --git a/XSB/packages/dbdrivers/mysql/configure.in b/XSB/packages/dbdrivers/mysql/configure.in
--- a/XSB/packages/dbdrivers/mysql/configure.in
+++ b/XSB/packages/dbdrivers/mysql/configure.in
@@ -18,7 +18,7 @@
 ## along with XSB; if not, write to the Free Software Foundation,
 ## Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 ##
-## $Id: configure.in,v 1.1 2003-09-29 09:40:02 kifer Exp $
+## $Id: configure.in,v 1.2 2008-02-15 06:54:40 kifer Exp $
 ## 
 ##
 
@@ -29,7 +29,7 @@ dnl  in the directory containing this script.
 dnl
 dnl
 
-AC_PREREQ(2.12)dnl
+AC_PREREQ(2.53)dnl
 
 AC_INIT(mysql_driver_config.P)
 
@@ -71,12 +71,26 @@ with_mysql=
 mysql_error=
 
 if test -z "$with_mysql_libdir" ; then
-   libdir="/usr/lib/mysql"
+   if test -d /usr/lib/mysql ; then
+      libdir="/usr/lib/mysql"
+   elif test -d /usr/local/lib/mysql ; then
+      libdir="/usr/local/lib/mysql"
+   else
+      echo "***Configuring MySQL failed: cannot find installation; please use the option --with-mysql-libdir"
+      exit 1
+   fi
 else
    libdir=$with_mysql_libdir
 fi
 if test -z "$with_mysql_incdir" ; then
-   incdir="/usr/include/mysql"
+   if test -d /usr/include/mysql ; then
+       incdir="/usr/include/mysql"
+   elif test -d /usr/local/mysql/include/mysql ; then
+       incdir="/usr/local/mysql/include/mysql"
+   else
+      echo "***Configuring MySQL failed: cannot find installation; please use the option --with-mysql-incdir"
+      exit 1
+   fi
 else
    incdir=$with_mysql_incdir
 fi
@@ -88,7 +102,7 @@ if test -n "$libdir" ; then
    LDFLAGS="-L${libdir} ${LDFLAGS}"
 fi
 
-AC_CHECK_LIB(mysqlclient, , mysql_error=yes)
+AC_CHECK_LIB(mysqlclient, main, , mysql_error=yes)
 # Here we provide additional directories to check headers in
 # AC_CHECK_HEADERS uses CPPFLAGS to find the include path.
 #
